nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*'] # Remplacez '*' par les origines spécifiques si nécessaire
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600